combine_control_expr = false
condense_wildcard_suffixes = true
fn_args_layout = "Vertical"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 120
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
unstable_features = true
